<img src="http://certificate.tpq.io/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# EPAT Session 1

**Executive Program in Algorithmic Trading**

**_Basics of Object Orientation_**

Prof. Dr. Yves J. Hilpisch | The Python Quants GmbH | http://tpq.io

<a href="https://home.tpq.io/certificates/pyalgo" target="_blank"><img src="https://hilpisch.com/pyalgo_cover_shadow.png" width="300px" align="left"></a>

## Introduction

In [70]:
class HumanBeing(object):  
    def __init__(self, first_name, eye_color):  
        self.first_name = first_name  
        self.eye_color = eye_color  
        self.position = 0  
    def walk_steps(self, steps):  
        self.position += steps  

In [71]:
Sandra = HumanBeing('Sandra', 'blue')  

In [72]:
Sandra.first_name  

'Sandra'

In [73]:
Sandra.position  

0

In [74]:
Sandra.walk_steps(5)  

In [75]:
Sandra.position  

5

In [76]:
Sandra.walk_steps(-2)

In [77]:
Sandra.position

3

## A Brief Look at Standard Objects

### int

In [78]:
n = 5  

In [79]:
type(n)  

int

In [80]:
n.numerator  

5

In [81]:
n.bit_length()  

3

In [82]:
n + n  

10

In [83]:
2 * n  

10

In [84]:
n.__sizeof__()  

28

### list

In [85]:
l = [1, 2, 3, 4]  

In [86]:
type(l)  

list

In [87]:
l[0]  

1

In [88]:
l.append(10)  

In [89]:
l + l  

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [90]:
2 * l  

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [91]:
sum(l)  

20

In [92]:
l.__sizeof__()  

104

### ndarray

In [93]:
import numpy as np  

In [94]:
a = np.arange(16).reshape((4, 4))  

In [95]:
a  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
type(a)  

numpy.ndarray

In [97]:
a.nbytes  

64

In [98]:
a.sum()  

120

In [99]:
a.cumsum(axis=0)  

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]], dtype=int32)

In [100]:
a + a  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [101]:
2 * a  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [102]:
sum(a)  

array([24, 28, 32, 36])

In [103]:
np.sum(a)  

120

In [104]:
a.__sizeof__()  

120

### DataFrame

In [105]:
import pandas as pd  

In [106]:
df = pd.DataFrame(a, columns=list('abcd'))  

In [107]:
type(df)  

pandas.core.frame.DataFrame

In [108]:
df.columns  

Index(['a', 'b', 'c', 'd'], dtype='object')

In [109]:
df.sum()  

a    24
b    28
c    32
d    36
dtype: int64

In [110]:
df.cumsum()  

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [111]:
df + df  

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [112]:
2 * df  

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [113]:
np.sum(df)  

a    24
b    28
c    32
d    36
dtype: int64

In [114]:
df.__sizeof__()  

192

## Basics of Python Classes

In [115]:
class FinancialInstrument(object):  
    pass  

In [116]:
fi = FinancialInstrument()  

In [117]:
type(fi)  

__main__.FinancialInstrument

In [118]:
fi  

In [119]:
fi.__str__()  

'<__main__.FinancialInstrument object at 0x000002670EA5AFA0>'

In [120]:
fi.price = 100  

In [121]:
fi.price  

100

In [122]:
class FinancialInstrument(object):
    author = 'Yves Hilpisch'  
    def __init__(self, symbol, price):  
        self.symbol = symbol  
        self.price = price  

In [123]:
FinancialInstrument.author  

'Yves Hilpisch'

In [124]:
aapl = FinancialInstrument('AAPL', 100)  

In [125]:
aapl.symbol  

'AAPL'

In [126]:
aapl.author  

'Yves Hilpisch'

In [127]:
aapl.price = 105  

In [128]:
aapl.price  

105

In [129]:
class FinancialInstrument(FinancialInstrument):  
    def get_price(self):  
        return self.price  
    def set_price(self, price):  
        self.price = price  

In [130]:
fi = FinancialInstrument('AAPL', 100)  

In [131]:
fi.get_price()  

100

In [132]:
fi.set_price(105)  

In [133]:
fi.get_price()  

105

In [134]:
fi.price  

105

In [145]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol  
        self.__price = price
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

In [146]:
fi = FinancialInstrument('AAPL', 100)

In [147]:
fi.get_price()  

100

In [153]:
fi._price()

AttributeError: 'FinancialInstrument' object has no attribute '_price'

In [150]:
fi.price

AttributeError: 'FinancialInstrument' object has no attribute 'price'

In [ ]:
fi._FinancialInstrument__price  

In [ ]:
fi._FinancialInstrument__price = 105  

In [ ]:
fi.set_price(100)  

In [ ]:
fi.get_price()

In [154]:
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument  
        self.__position_size = position_size  
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * \
               self.position.get_price()  

In [155]:
pp = PortfolioPosition(fi, 10)

In [156]:
pp.get_position_size()

10

In [157]:
pp.get_position_value()  

1000

In [158]:
pp.position.get_price()  

100

In [159]:
pp.position.set_price(105)  

In [160]:
# new_price = data_source.get_price()

In [161]:
# pp.position.set_price(new_price)  

In [162]:
pp.get_position_value()  

1050

## Python Data Model

In [163]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):  
        self.x = x  
        self.y = y  
        self.z = z  

In [164]:
v = Vector(1, 2, 3)  

In [165]:
v  

In [166]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

In [167]:
v = Vector(1, 2, 3)

In [168]:
v  

Vector(1, 2, 3)

In [169]:
print(v)  

Vector(1, 2, 3)


In [170]:
abs(-2)

2

In [171]:
True

True

In [172]:
False

False

In [173]:
type(True)

bool

In [174]:
int(False)

0

In [175]:
a = 4
b = 4

In [176]:
a == b

True

In [177]:
5 == 4

False

In [178]:
int(True)

1

In [179]:
bool(10)

True

In [180]:
bool(0)

False

In [181]:
bool(-1)

True

In [182]:
class Vector(Vector):
    def __abs__(self):
        return (self.x ** 2 +  self.y ** 2 +
                self.z ** 2) ** 0.5  
    
    def __bool__(self):
        return bool(abs(self))

In [183]:
v = Vector(1, 2, -1)  

In [184]:
v

Vector(1, 2, -1)

In [185]:
abs(v)

2.449489742783178

In [186]:
bool(v)

True

In [187]:
v = Vector()

In [188]:
v  

Vector(0, 0, 0)

In [189]:
abs(v)

0.0

In [190]:
bool(v)

False

In [191]:
v + v

TypeError: unsupported operand type(s) for +: 'Vector' and 'Vector'

In [192]:
2 * v

TypeError: unsupported operand type(s) for *: 'int' and 'Vector'

In [193]:
class Vector(Vector):
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)  
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)  

In [194]:
v = Vector(1, 2, 3)

In [195]:
v + Vector(2, 3, 4)

Vector(3, 5, 7)

In [196]:
v * 2

Vector(2, 4, 6)

In [197]:
len(v)

TypeError: object of type 'Vector' has no len()

In [198]:
v[0]

TypeError: 'Vector' object is not subscriptable

In [199]:
class Vector(Vector):
    def __len__(self):
        return 3  
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [200]:
v = Vector(1, 2, 3)

In [201]:
len(v)

3

In [202]:
v[0]

1

In [203]:
v[-2]

2

In [204]:
v[3]

IndexError: Index out of range.

In [205]:
class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [206]:
v = Vector(1, 2, 3)

In [207]:
for i in range(3):  
    print(v[i])  

1
2
3


In [208]:
for coordinate in v:  
    print(coordinate)  

1
2
3


In [209]:
def special_operation(Vector1, Vector2):
    return 'desired behaviour'

In [210]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z
    
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)
    
    def __abs__(self):
        return (self.x ** 2 +  self.y ** 2 + self.z ** 2) ** 0.5
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)
    
    def __len__(self):
        return 3
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')
            
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

<img src="http://certificate.tpq.io/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>